name: deploy

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Install gtest
        run: |
          sudo apt-get install libgtest-dev libboost-all-dev
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib
          sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
          sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - uses: actions/checkout@v1
      - name: CMake
        run: |
          mkdir build
          cd build
          cmake ..
      - name: make
        run: cd build && make
      - name: Run tests
        run: build/run_tests
      - name: Package binary
        shell: bash
        run: |
          cd build
          strip planarityfilter
          tar -czvf planarityfilter.tar.gz planarityfilter

          shasum -a 256 planarityfilter.tar.gz > planarityfilter.sha256
      - name: Release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/planarityfilter.tar.gz
            build/planarityfilter.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
